aviato/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('mainsite.urls')),
    
    path('accounts/', include('account.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainsite/urls.py
from django.urls import path
from . import views

app_name = 'mainsite'
urlpatterns = [
    path('', views.home, name='home'),

    path('detail/<model_name>/<id>/', views.content_view, name='content_detail'),

    path('create/<model_name>/', views.ContentCreateUpdateView.as_view(), name='create_content'),

    path('update/<model_name>/<id>/', views.ContentCreateUpdateView.as_view(), name='update_content'),
    
    path('delete/<model_name>/<id>/', views.delete_content , name='content_delete'),

    path('discovery/', views.discovery, name='discovery'),

    path('like', views.content_like, name='like')

]

mainsite/models.py
from django.contrib.auth.models import User
from django.db import models
from model_utils.managers import InheritanceManager
from django.conf import settings

class BaseItem(models.Model):
    objects = InheritanceManager()
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='content_liked')
    total_likes = models.PositiveIntegerField(db_index=True, default=0)
    
    def __str__(self):
        return f'{self.owner}'

class Text(BaseItem):
    file_image = models.ImageField(upload_to='images')
    content = models.TextField()

class Video(BaseItem):
    file_image = models.ImageField(upload_to='images')
    url = models.URLField()

class File(BaseItem):
    file_image = models.ImageField(upload_to='images')
    file_stuff = models.FileField(upload_to='files')

class Image(BaseItem):
    file_image = models.ImageField(upload_to='images')

mainsite/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from .models import BaseItem
from django.apps import apps
from django.views.generic.base import TemplateResponseMixin, View
from django.forms.models import modelform_factory
from django.http import Http404, JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from common.decorators import ajax_required
from django.views.decorators.http import require_POST

def home(request):
    following_ids = request.user.following.values_list('id', flat=True)
    all_stuff = None
    if following_ids:
        all_stuff = BaseItem.objects.all().order_by('-created').select_subclasses().filter(owner_id__in=following_ids)
    
    return render(request, 'main/home.html', {'all_stuff': all_stuff})
    
def discovery(request):
    all_stuff = BaseItem.objects.all().order_by('-created').select_subclasses()
    return render(request, 'main/discovery.html', {'all_stuff': all_stuff})


def content_view(request, model_name, id):
    if model_name in ['image', 'text', 'video', 'file']:
        model = apps.get_model(app_label='mainsite', model_name=model_name)
        content = get_object_or_404(model, id=id)
    else:
        raise Http404

    return render(request, 'content/detail.html', {'content': content, 'request':request})

class OwnerMixin(object):
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(owner=self.request.user)
    

class ContentCreateUpdateView(TemplateResponseMixin, View, OwnerMixin):
    model = None
    obj = None
    template_name = 'content/form.html'

    def get_model(self, model_name):
        if model_name in ['text', 'video', 'image', 'file']:
            return apps.get_model(app_label='mainsite', model_name=model_name)
        return None

    def get_form(self, model, *args, **kwargs):
        Form = modelform_factory(model, exclude=['owner', 'created', 'updated'])
        return Form(*args, **kwargs)

    def dispatch(self, request, model_name, id=None):
        self.model = self.get_model(model_name)
        if id:
            self.obj = get_object_or_404(self.model, id=id, owner=request.user)
        return super().dispatch(request, model_name, id)

    def get(self, request, model_name, id=None):
        form = self.get_form(self.model, instance=self.obj)
        return self.render_to_response({'form': form, 'object':self.obj})

    def post(self, request, model_name, id=None):
        form = self.get_form(self.model, instance=self.obj, data=request.POST, files=request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.owner = request.user
            obj.save()
            return redirect('mainsite:home')
        return self.render_to_response({'form':form, 'object':self.obj})

def delete_content(request, model_name, id):
    if model_name in ['text', 'video', 'image', 'file']:
        model = apps.get_model(app_label='mainsite', model_name=model_name)
    content = get_object_or_404(model, id=id, owner=request.user)
    content.delete()
    return redirect('mainsite:home')

@ajax_required
@login_required
@require_POST
def content_like(request):
    content_id = request.POST.get('id')
    action = request.POST.get('action')
    model = request.POST.get('model')

    if content_id and action and model:
        if model in ['text', 'image', 'video', 'file']:
            content_model = apps.get_model(app_label='mainsite', model_name=model)
            content = content_model.objects.get(id=content_id)
        try:
            if action == 'like':
                content.users_like.add(request.user)
            else:
                content.users_like.remove(request.user)
            return JsonResponse({'status':'ok'})
        except:
            return JsonResponse({'status':'error'})

mainsite/templates/content/detail.html
{% extends 'base.html'%}
{% load thumbnail %}
{% load embed_video_tags %}
{% load course %}
{% block title %}{{ content|model_name }}{% endblock %}
{% block content %}
{% load user_intro %}
<!-- profile -->

<div class="card mb-3 w-25 p-3 mx-auto my-4">
  <img src="{{ content.file_image.url }}" class="card-img-top" alt="...">
  <div class="card-body">
    <p class="card-text"><small class="text-muted">Last updated {{ content.updated|date:"d M Y" }} ||
        created at{{ content.created|date:"d M Y" }}
        </small></p>
        <p class="card-text"><small class="text-muted">autor: {{ content.owner.get_full_name }}</small></p>
    <div style="background-color: rgba(248, 239, 220, 0.685); border-radius: 10px;" class="p-2 ">
        <p class="card-text" >{{ content.description|linebreaks}}</p>
    </div>
    {% if content|model_name == 'text' %}
        <p class="card-text">{{ content.content|linebreaks }}</p>
    {% elif content|model_name == 'video' %}
        {% video content.url '410x280' %}
    {% elif content|model_name == 'file' %}
        <a class="btn btn-primary w-100 my-3 " href="{{ content.file_stuff.url }}" class="button">Download file</a>
    {% endif %}
  </div>
  {% if request.user == content.owner %}
  <div class="btn-group" role="group" aria-label="...">
    <a href="{% url 'mainsite:update_content' content|model_name content.id %}" type="button" class="btn btn-primary">edit</a>
    <a href="{% url 'mainsite:content_delete' content|model_name content.id %}" type="button" class="btn btn-danger">delet</a>
  </div>
  {% endif %}
  {% with total_likes=content.users_like.count users_like=content.users_like.all %}
  <a href="#" data-model="{{ content|model_name }}" data-id="{{ content.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" style="background-color: rgb(255, 51, 0); width: 60px; color: white;" class="like button p-1 m-3">
          {% if request.user not in users_like %}
            Like
          {% else %}
            Unlike
          {% endif %}
        </a>

    <span>{{ total_likes|slice:":5" }} like</span>
    <div style="display: flex; flex-direction: row;">
    {% for like in users_like %}
    <img src="{{ like.profile.photo|thumbnail_url:'user_like' }}" alt="" style="width: 25px; border-radius: 25px;">
    {% endfor %}
    </div>
  {% endwith %}
</div>
{% endblock %}



{% block domready %}
  $('a.like').click(function(e){
    e.preventDefault();
    $.post('{% url "mainsite:like" %}',
      {
        model: $(this).data('model'),
        id: $(this).data('id'),
        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok')
        {
          var previous_action = $('a.like').data('action');

          // toggle data-action
          $('a.like').data('action', previous_action == 'like' ?
          'unlike' : 'like');
          // toggle link text
          $('a.like').text(previous_action == 'like' ? 'Unlike' :
          'Like');

          // update total likes
          var previous_likes = parseInt($('span.count .total').text());
          $('span.count .total').text(previous_action == 'like' ?
          previous_likes + 1 : previous_likes - 1);
        }
      }
    );
  });
{% endblock %}

mainsite/templates/content/form.html
{% extends "base.html" %}

{% block title %}
  {% if object %}
    Edit content
  {% else %}
    Add new content
  {% endif %}
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="card w-50 mx-auto my-3 p-2">
  <h1>
    {% if object %}
      Edit content
    {% else %}
      Add new content
    {% endif %}
  </h1>
  <div class="module">
    <form method="post" enctype="multipart/form-data">
      {{ form|crispy }}
      {% csrf_token %}
      <input type="submit" value="Save content" class="btn btn-primary w-100">
    </form>
  </div>

</div>
{% endblock %}