aviato/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('mainsite.urls')),
    
    path('accounts/', include('account.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainsite/urls.py
from django.urls import path
from . import views

app_name = 'mainsite'
urlpatterns = [
    path('', views.home, name='home'),

    path('detail/<model_name>/<id>/', views.content_view, name='content_detail'),

    path('create/<model_name>/', views.ContentCreateUpdateView.as_view(), name='create_content'),

    path('update/<model_name>/<id>/', views.ContentCreateUpdateView.as_view(), name='update_content'),
    
    path('delete/<model_name>/<id>/', views.delete_content , name='content_delete'),

    path('discovery/', views.discovery, name='discovery'),

    path('like', views.content_like, name='like')

]

mainsite/models.py
from django.contrib.auth.models import User
from django.db import models
from model_utils.managers import InheritanceManager
from django.conf import settings

class BaseItem(models.Model):
    objects = InheritanceManager()
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='content_liked')
    total_likes = models.PositiveIntegerField(db_index=True, default=0)
    
    def __str__(self):
        return f'{self.owner}'

class Text(BaseItem):
    file_image = models.ImageField(upload_to='images')
    content = models.TextField()

class Video(BaseItem):
    file_image = models.ImageField(upload_to='images')
    url = models.URLField()

class File(BaseItem):
    file_image = models.ImageField(upload_to='images')
    file_stuff = models.FileField(upload_to='files')

class Image(BaseItem):
    file_image = models.ImageField(upload_to='images')

mainsite/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from .models import BaseItem
from django.apps import apps
from django.views.generic.base import TemplateResponseMixin, View
from django.forms.models import modelform_factory
from django.http import Http404, JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from common.decorators import ajax_required
from django.views.decorators.http import require_POST

def home(request):
    following_ids = request.user.following.values_list('id', flat=True)
    all_stuff = None
    if following_ids:
        all_stuff = BaseItem.objects.all().order_by('-created').select_subclasses().filter(owner_id__in=following_ids)
    
    return render(request, 'main/home.html', {'all_stuff': all_stuff})
    
def discovery(request):
    all_stuff = BaseItem.objects.all().order_by('-created').select_subclasses()
    return render(request, 'main/discovery.html', {'all_stuff': all_stuff})


def content_view(request, model_name, id):
    if model_name in ['image', 'text', 'video', 'file']:
        model = apps.get_model(app_label='mainsite', model_name=model_name)
        content = get_object_or_404(model, id=id)
    else:
        raise Http404

    return render(request, 'content/detail.html', {'content': content, 'request':request})

class OwnerMixin(object):
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(owner=self.request.user)
    

class ContentCreateUpdateView(TemplateResponseMixin, View, OwnerMixin):
    model = None
    obj = None
    template_name = 'content/form.html'

    def get_model(self, model_name):
        if model_name in ['text', 'video', 'image', 'file']:
            return apps.get_model(app_label='mainsite', model_name=model_name)
        return None

    def get_form(self, model, *args, **kwargs):
        Form = modelform_factory(model, exclude=['owner', 'created', 'updated'])
        return Form(*args, **kwargs)

    def dispatch(self, request, model_name, id=None):
        self.model = self.get_model(model_name)
        if id:
            self.obj = get_object_or_404(self.model, id=id, owner=request.user)
        return super().dispatch(request, model_name, id)

    def get(self, request, model_name, id=None):
        form = self.get_form(self.model, instance=self.obj)
        return self.render_to_response({'form': form, 'object':self.obj})

    def post(self, request, model_name, id=None):
        form = self.get_form(self.model, instance=self.obj, data=request.POST, files=request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.owner = request.user
            obj.save()
            return redirect('mainsite:home')
        return self.render_to_response({'form':form, 'object':self.obj})

def delete_content(request, model_name, id):
    if model_name in ['text', 'video', 'image', 'file']:
        model = apps.get_model(app_label='mainsite', model_name=model_name)
    content = get_object_or_404(model, id=id, owner=request.user)
    content.delete()
    return redirect('mainsite:home')

@ajax_required
@login_required
@require_POST
def content_like(request):
    content_id = request.POST.get('id')
    action = request.POST.get('action')
    model = request.POST.get('model')

    if content_id and action and model:
        if model in ['text', 'image', 'video', 'file']:
            content_model = apps.get_model(app_label='mainsite', model_name=model)
            content = content_model.objects.get(id=content_id)
        try:
            if action == 'like':
                content.users_like.add(request.user)
            else:
                content.users_like.remove(request.user)
            return JsonResponse({'status':'ok'})
        except:
            return JsonResponse({'status':'error'})

mainsite/templates/main/discovery.html
{% extends 'base.html'%}
{% load thumbnail %}
{% load course %}
{% block title %}Aviato{% endblock %}
{% block content %}
{% load user_intro %}
<!-- profile -->
 {% for stuff in all_stuff %}
 <div class="card mb-3 w-50 p-3 mx-auto my-4" >
    <div class="row no-gutters">
      <div class="col-md-4">
        <a href="{% url 'mainsite:content_detail' stuff|model_name stuff.id %}">
          <img src="{{ stuff.file_image.url }}" class="card-img" alt="..." style="max-width: 100px;">
        </a>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <p class="card-text">{{ stuff.description|truncatewords:20 }}</p>
          <span class="badge badge-warning">{{ stuff|model_name }}</span>
          <p class="card-text"><small class="text-muted">Last updated {{ stuff.updated|date:"d M Y" }}</small></p>
        </div>
      </div>
    </div>
  </div>
 {% endfor %}
<!-- end profile  -->
{% endblock %}

mainsite/templates/main/home.html
{% extends 'base.html'%}
{% load thumbnail %}
{% load course %}
{% block title %}Aviato{% endblock %}
{% block content %}
{% load user_intro %}
<!-- profile -->
{% if user.is_authenticated %}
{% user_profile_intro %}
{% endif %}
{% if all_stuff %}
 {% for stuff in all_stuff %}
 <div class="card mb-3 w-50 p-3 mx-auto my-4" >
    <div class="row no-gutters">
      <div class="col-md-4">
        <a href="{% url 'mainsite:content_detail' stuff|model_name stuff.id %}">
          <img src="{{ stuff.file_image.url }}" class="card-img" alt="..." style="max-width: 100px;">
        </a>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <p class="card-text">{{ stuff.description|truncatewords:20 }}</p>
          <span class="badge badge-warning">{{ stuff|model_name }}</span>
          <p class="card-text"><small class="text-muted">Last updated {{ stuff.updated|date:"d M Y" }}</small></p>
          <p class="card-text"><small class="text-muted">autor: {{ stuff.owner.get_full_name }}</small></p>
        </div>
      </div>
    </div>
  </div>
 {% endfor %}
{% else %}

<div class="card mb-3 w-50 p-3 mx-auto my-4" >
  <a href="{% url 'mainsite:discovery'%}" class="btn btn-outline-success">discovery</a>
  </div>
{% endif %}

<!-- end profile  -->
{% endblock %}

mainsite/templates/main/user_intro.html
{% load thumbnail %}
{% if user %}
<div class="card w-50 p-3 mx-auto my-4" >
    <div class="card-body  justify-content-around" >
    <div class="d-flex flex-row">
      <img style="border-radius: 50%; width: 100px;" src="{{ user.profile.photo|thumbnail_url:'avatar' }}" alt="" />
      <div style="margin-left:30px;">
      <h5 class="card-title">{{ user.get_full_name }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">born: {{ user.profile.date_of_brith|date:"d M Y" }}</h6>
      <h6 class="card-subtitle mb-2 text-muted">join: {{ user.profile.created| date:"d M Y" }}</h6>
      </div>
    </div>
      <div style="padding:20px 20px;">
        <p class="card-text">{{ user.profile.bio }}</p>
        <div style="display: flex; flex-direction: row;">
          <a href="" class="btn btn-outline-primary" style="height: 39px; margin-right: 3px;">followers: {{ user.followers.count }}</a>
          <a href="" class="btn btn-outline-primary" style="height: 39px;">following: {{ user.following.count }}</a>
          <a href="" class="btn btn-outline-primary" style="height: 39px; margin-left: 3px;">posts: {{ post_count }}</a>
        <a href="{% url 'user_settings'%}" class="card-link p-2"><span style="color: rgb(71, 68, 68);" class="material-icons">settings</span></a>
        <div class="dropdown">
          <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            add
          </a>
        
          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="{% url 'mainsite:create_content' 'video' %}"><span class="material-icons">
              play_circle_outline
              </span></a>
            <a class="dropdown-item" href="{% url 'mainsite:create_content' 'file' %}"><span class="material-icons">
              create_new_folder
              </span></a>
            <a class="dropdown-item" href="{% url 'mainsite:create_content' 'image' %}"><span class="material-icons">
              add_photo_alternate
              </span></a>
            <a class="dropdown-item" href="{% url 'mainsite:create_content' 'text' %}"><span class="material-icons">
              title
              </span></a>
          </div>
        </div>
      </div>
      </div>
    </div>
</div>
{% else %}
hello
{% endif %}